name: CI-CD

on: [push]

jobs:
  build:

    runs-on: python:3.10-slim

    steps:
    - name: checkout mlops repository
      uses: actions/checkout@v1
    # - name: setup python
    #   uses: actions/setup-python@v4
    #   with:
    #       python-version: '3.10'
    # - name: install project dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt
    - name: Build Docker Container
      run: docker build -t cicdmlops:latest .

  test:
    runs-on: python:3.10-slim

    steps:
    - name: checkout mlops repository
      uses: actions/checkout@v1
    - name: setup python
      uses: actions/setup-python@v4
      with:
          python-version: '3.10'
    - name: install project dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        pytest tests -m predict
        pytest tests -m dataValidation

  deploy:
    runs-on: python:3.10-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-north-1"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t cicdmlops:latest .
          docker tag cicdmlops:latest ${{ steps.login-ecr.outputs.registry }}/cicdmlops:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/cicdmlops:latest